#!/usr/bin/env python3
"""Regenerate docs/CODEMAP.md — one line per Swift file: size, public types, purpose.

    scripts/codemap.py          # rewrite docs/CODEMAP.md if it changed
    scripts/codemap.py --check  # exit 1 if the map is stale (new/moved/renamed files)
    scripts/codemap.py --quiet  # same as no flag, but silent (used by the Stop hook)

Sizes are rounded to 0.1k lines so ordinary edits don't churn the file.

The purpose column is the first sentence of the doc comment on the type named after the
file (or on its first type), so the way to improve a line here is to improve that comment.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "CODEMAP.md")
TARGETS = [
    ("Equitrip", "iOS app"),
    ("EquitripShared", "compiled into app + widgets + watch (see membership exceptions in project.pbxproj)"),
    ("EquitripWidgets", "WidgetKit extension: widgets, controls"),
    ("EquitripWatch Watch App", "watchOS app, fed by WatchConnectivity snapshots"),
]
DECL = re.compile(
    r"^(?:(?:public|internal|final|nonisolated|indirect)\s+)*"
    r"(struct|enum|class|actor|protocol|extension)\s+([A-Za-z_][\w.]*)"
)
ATTRIBUTE = re.compile(r"^@\w+")
MAX_TYPES = 6
MAX_PURPOSE = 110


def size(lines):
    return "%.1fk" % max(0.1, round(lines / 100) / 10)


def first_sentence(doc_lines):
    text = " ".join(l.strip()[3:].strip() for l in doc_lines).strip()
    text = re.sub(r"\s+", " ", text)
    match = re.match(r"(.+?[.!?])(\s|$)", text)
    sentence = match.group(1) if match else text
    if len(sentence) > MAX_PURPOSE:
        sentence = sentence[: MAX_PURPOSE - 1].rstrip() + "…"
    return sentence


def describe(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    stem = os.path.splitext(os.path.basename(path))[0]
    types, extensions, docs = [], [], {}
    for index, line in enumerate(lines):
        match = DECL.match(line)
        if not match:
            continue
        kind, name = match.groups()
        (extensions if kind == "extension" else types).append(name)
        if name in docs:
            continue
        # Walk up over attributes to the doc comment directly above.
        cursor = index - 1
        while cursor >= 0 and ATTRIBUTE.match(lines[cursor]):
            cursor -= 1
        doc = []
        while cursor >= 0 and lines[cursor].lstrip().startswith("///"):
            doc.insert(0, lines[cursor])
            cursor -= 1
        # Only the first paragraph.
        paragraph = []
        for l in doc:
            if l.strip() == "///":
                break
            paragraph.append(l)
        docs[name] = first_sentence(paragraph) if paragraph else ""
    # The type named after the file speaks for it; otherwise the first type does,
    # unless the file is a grab-bag where no one type's comment describes the rest.
    if docs.get(stem):
        purpose = docs[stem]
    elif types and len(types) <= 2:
        purpose = docs.get(types[0], "")
    else:
        purpose = ""
    names = types or ["ext " + e for e in dict.fromkeys(extensions)]
    if len(names) > MAX_TYPES:
        names = names[:MAX_TYPES] + ["+%d" % (len(names) - MAX_TYPES)]
    return len(lines) - (1 if lines and lines[-1] == "" else 0), names, purpose


def render():
    out = [
        "# Code map",
        "",
        "<!-- Generated by scripts/codemap.py — do not edit by hand. -->",
        "",
        "`file (size in lines) — top-level types — purpose`. Private helpers omitted. "
        "Regenerate after adding, moving or renaming files.",
        "",
    ]
    for target, blurb in TARGETS:
        base = os.path.join(ROOT, target)
        files = []
        for folder, dirs, names in os.walk(base):
            dirs[:] = sorted(d for d in dirs if not d.endswith((".xcassets", ".lproj")))
            files += [os.path.join(folder, n) for n in sorted(names) if n.endswith(".swift")]
        total = 0
        body = []
        current_group = None
        for path in files:
            rel = os.path.relpath(path, base)
            group = os.path.dirname(rel) or "(root)"
            if group != current_group:
                body += ["", "**%s/**" % group if group != "(root)" else "**(root)**"]
                current_group = group
            count, names, purpose = describe(path)
            total += count
            line = "- `%s` (%s) — %s" % (os.path.basename(rel), size(count), ", ".join(names) or "—")
            if purpose:
                line += " — " + purpose
            body.append(line)
        out.append("## %s — %s" % (target, blurb))
        out.append("")
        out.append("%d files, %dk lines." % (len(files), round(total / 1000)))
        out += body
        out.append("")
    return "\n".join(out)


def main():
    text = render()
    current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    quiet = "--quiet" in sys.argv
    if "--check" in sys.argv:
        if current != text:
            print("docs/CODEMAP.md is stale — run scripts/codemap.py")
            sys.exit(1)
        print("docs/CODEMAP.md is current")
        return
    if current == text:
        quiet or print("docs/CODEMAP.md already current")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    quiet or print("wrote docs/CODEMAP.md (%d bytes)" % len(text.encode()))


if __name__ == "__main__":
    main()
